name: Full Test
on:
  pull_request_review:
    types: [submitted]

env:
  INTEGRATION_TEST_SPREADSHEET_ID: ${{ secrets.INTEGRATION_TEST_SPREADSHEET_ID }}
  INTEGRATION_TEST_AUTH_JSON: ${{ secrets.INTEGRATION_TEST_AUTH_JSON }}

jobs:
  full_test:
    runs-on: ubuntu-latest
    environment: integration_test
    strategy:
      matrix:
        go-version: ['1.18.x']

    if: github.event.review.state == 'approved'

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Golang version
        run: go version

      - name: Full Test
        run: |
          go test -v -count=1 -cover ./... -coverprofile coverage.out -coverpkg ./...
          go tool cover -func coverage.out -o coverage.out