name: Unit Test
on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.17.x', '1.18.x']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Golang version
        run: go version

      - name: Unit test
        run: go test -v ./... -count=1