name: Unit Test
on: push

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.22.x', '1.23.x']

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          # As there is only one Golang script being run.
          # Faster if we don't cache as the cache is per commit anyway.
          cache: false

      - name: Golang version
        run: go version

      - name: Unit test
        run: go test -v -cover -count=1 ./...
